// Landing page components
export { Hero } from './hero'
export { ProductOverview } from './product-overview'
export { ProblemsSolved } from './problems-solved'
export { AIAssistantFeatures } from './ai-assistant-features'
export { GstnIntegration } from './gstn-integration'
export { GstPortalTrust } from './gst-portal-trust'
export { TrustFAQ } from './trust-faq'
export { WhatsAppBot } from './whatsapp-bot'
export { CoreCapabilities } from './core-capabilities'
export { HowItWorks } from './how-it-works'
export { AICapabilities } from './ai-capabilities'
export { AnalyticsDashboards } from './analytics-dashboards'
export { MobileApp } from './mobile-app'
export { SecurityScalability } from './security-scalability'
export { WhyChooseUs } from './why-choose-us'
export { PricingPreview } from './pricing-preview'
export { CTASection } from './cta-section'
export { LandingHeader } from './landing-header'
export { LandingFooter } from './landing-footer'
export { WorkflowDiagram } from './workflow-diagram'
export { FeatureCard } from './feature-card'
export { StatCard } from './stat-card'
export { AnimatedCounter } from './animated-counter'

// Audience-specific sections
export { BusinessOwnerSection } from './business-owner-section'
export { TaxProfessionalSection } from './tax-professional-section'
export { FinanceTeamSection } from './finance-team-section'
